/cmd_vel:
  type: geometry_msgs/msg/Twist
  vx:
    min: -0.8
    max: 0.8
    to: linear.x
    default: 0.
  vy:
    min: -1
    max: 1
    to: linear.y
    default: 0.
  vz:
    min: -1
    max: 1
    to: linear.z
    default: 0.
  wx:
    min: -1
    max: 1
    to: angular.x
    default: 0.
  wy:
    min: -1
    max: 1
    to: angular.y
    default: 0.
  wz:
    min: -1
    max: 1
    to: angular.z
    default: 0.
