controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    xy_unilivers_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    xy_unilivers_position_controller:
      #https://control.ros.org/humble/doc/ros2_controllers/position_controllers/doc/userdoc.html
      type: position_controllers/JointGroupPositionController

    xy_unilivers_joint_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    xy_unilivers_secured_1d_velocity_controller:
      type: secured_1d_velocity_controller/Secured1dVelocityController

xy_unilivers_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - base_to_charriot

xy_unilivers_position_controller:
  ros__parameters:
    joints:
      - base_to_charriot

xy_unilivers_joint_velocity_controller:
  ros__parameters:
    joints:
      - base_to_charriot

xy_unilivers_secured_1d_velocity_controller:
  ros__parameters:
    joints:
      - base_to_charriot
